apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
  namespace: team-rakett
spec:
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
        - image: ttl.sh/aggregator:2m
          name: aggregator
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      securityContext:
        runAsUser: 10002
