apiVersion: v1
kind: Service
metadata:
  name: aggregator
  namespace: team-rakett
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: aggregator
  type: ClusterIP
