apiVersion: apps/v1
kind: Deployment
metadata:
  name: normalizer
  namespace: team-rakett
spec:
  selector:
    matchLabels:
      app: normalizer
  template:
    metadata:
      labels:
        app: normalizer
    spec:
      containers:
        - image: ttl.sh/normalizer:latest
          name: normalizer
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      securityContext:
        runAsUser: 10002
