apiVersion: v1
kind: Service
metadata:
  name: normalizer
  namespace: team-rakett
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: normalizer
  type: ClusterIP
